@startuml

package "Class diagram for Service Classes" #E1DFEB {

    class GameManager {
        gameDuration : int
        timeElapsed : int
        + init()
        + tick()
        + evaluateGame()
    }

    class GameSaver {
        + save(f : File)
        + load(f : File)
    }

    class ScoreBoard {
        + update()
    }
}

@enduml