@startuml CD_InGameObjects

package "Class diagram for In-Game Objects" #E1DFEB {
    
    'world elements'

    class Map {
        + List<Continent> continents
        + tick()
    }

    class Continent {
        + breakChance : double
        + break()
        + getNeighbours()
        + getChildTiles()
        + increaseBreakChance(...)
    }

    class Tile {
        + getNeighbours()
        + growthRate
        + maxMycelium
        + List<Mycelium> myceliums
        + List<Spore> spores
        + List<Insect> insects
        + List<MushroomBody> mushroomBodies
        + getParentContinent()
    }

    'interactive elements'

    abstract class Entity {
        + currentTile : Tile
        + getCurrentTile()
    }

    class Mycelium {
        + isConnected
        + remainingTime
        + rot()
        + revive()
    }

    class Spore {
        nutrientScore
        + getNutrient()
        + getTile()
    }

    'playable elements'

    abstract class Player {
        + List<ScoreType> score
        + List<Effect> effects
        + pickStartingTile(t : Tile)
        + endTurn()
        + calculateScore()
    }

    class MushroomPlayer {
        + placeMushroomHeadTo(t : Tile)
        + placeMyceliumTo(t : Tile)
        + placeBodyTo(t : Tile)
    }

    class MushroomBody {
        + smallSpread()
        + largeSpread()
    }
    
    class InsectPlayer {
        + moveTo(t : Tile)
        + eat(s : Spore)
        + cut(m : Mycelium)
    }

    class Insect {

    }

    'connections'

    Player --|> Entity
    Spore --|> Entity
    Continent "1" --o "1" Map
    MushroomBody "1" --o "1" Continent
    Tile "*" --* "1" Continent
    Mycelium "1" --o "1" Tile
    Insect -> Spore
    Spore "1" --o "1" Tile
    MushroomPlayer --|> Player
    InsectPlayer --|> Player
    Insect "1" --* "1" InsectPlayer
    MushroomBody "*" --* "1" MushroomPlayer
}

@enduml