@startuml Fungus growth with spore

title Mycelium can't grow on Tekton

participant "f : Fungus" as F
participant "tek: Tekton" as Tek

activate F
activate Tek


F->Tek : growMycelium()
Tek --> F : false 



@enduml