@startuml Fungus spores

title Fungus spreading spores

participant "fb : FungusBody" as Fb
participant "t : Tile" as T
participant "s : Spore" as S

activate Fb
activate T

opt have enough points to spread
loop 
Fb -> S ** : <<construct>>
activate S
S --> Fb
Fb -> T : addEntity(s)
T-->Fb

end
end


@enduml