@startuml Fungus growth

title Fungus growing mycelium

participant "f : Fungus" as F
participant "t : Tile" as T
participant "m : Mycelium" as M

activate F
activate T


F-[#red]>T : growMycelium
opt have enough points
F -> M ** : construct
F -> T : addEntity

end


@enduml