@startuml Fungus growth

title Fungus growing mycelium

actor "Player controlling the fungus" as P
actor "FungusPlayer" as Fp
actor "Fungus" as F
actor "Tile" as T
actor "Mycelium" as M

activate P
activate Fp
activate F
activate T

P --> Fp : PlaceMycelium
opt have enough points
Fp -> F : growMycelium
F -> M ** : construct
F -> T : addEntity
F --> Fp
Fp -> Fp : updateScore

end


@enduml