@startuml Fungus mushroom

title Fungus growing a mushroom

participant "f : Fungus" as F
participant "t : Tile" as T
participant "fb : FungusBody" as Fb

activate F
activate T

opt have enough points
F -> Fb ** : <<construct>>
activate Fb
Fb --> F
F -> T : addEntity(fb)


end


@enduml