@startuml Fungus mushroom

title Fungus growing a mushroom

participant "F : Fungus" as F
participant "T : Tile" as T
participant "Fb : FungusBody" as Fb

activate F
activate T

opt have enough points
F -> Fb ** : <<construct>>
activate Fb
Fb --> F
F -> T : addEntity(Fb)


end


@enduml