@startuml Fungus spores

title Fungus spreading spores

actor "Player controlling the fungus" as P
actor "FungusPlayer" as Fp
actor "FungusBody" as Fb
actor "Tile" as T
actor "Spore" as S

activate P
activate Fp
activate Fb
activate T

P --> Fp : sporeCloud
opt have enough points to spread
Fp -> Fb : sporeCloud
Fb -> S ** : construct
Fb -> T : addEntity
Fb --> Fp
Fp -> Fp : updateScore

end


@enduml