@startuml Fungus growth with spore

title Fungus growing mycelium with spore

participant "f : Fungus" as F
participant "t : Tile" as T
participant "m : Mycelium" as M

activate F
activate T


F-[#red]>T : growMycelium
opt have enough points
T -[#red]> F : hasSpore
F -> M ** : construct
F -> T : addEntity

end


@enduml