@startuml Fungus growth with spore

title Fungus growing mycelium with spore

participant "f : Fungus" as F
participant "tek: Tekton" as Tek
participant "m : Mycelium" as M
participant "t : Tile" as T

activate F
activate T


F-[#red]>Tek : growMycelium()
Tek -[#red]> F : hasSpore()
F -> M ** : <<construct>>
F -> T : addEntity()



@enduml