@startuml Insect thread cutting

title Insect cutting a thread


participant "i : Insect" as I
participant "m : Mycelium" as T
participant "t : Tile" as Tl
participant "connected : Mycelium" as Mc
participant "disconnected : Mycelium" as Md


activate I
activate T
activate Tl

opt Insect not under the influence of CutSpore
I -> T : detach()
T->Mc : <<construct>>

activate Mc

Mc-->T
T->Tl : addEntity(connected)
Tl --> T
T->Md : <<construct>>

activate Md

Md-->T
T->Tl : addEntity(disconnected)
Tl-->T

T->Tl : removeEntity(m)
Tl-->T

destroy T

end


@enduml