@startuml Insect thread cutting

title Insect cutting a thread

actor "Player controlling the insect" as P
actor "InsectPlayer" as Ip
actor "Insect" as I
actor "Mycelium" as T

activate P
activate Ip
activate I
activate T

P --> Ip : cut

Ip -> I : cut
opt not under the influence of CutSpore
I -> T : detach


end


@enduml