@startuml Insect eating

title Insect player eating a spore

participant "I : Insect" as I
participant "Sp : Spore" as Sp
participant "T : Tile" as T

activate I
activate T
activate Sp

I -> Sp : getEaten(I)
alt Sp is a CutSpore 
ref over I, Sp : Cut spore affecting insect
else Sp is a FreezeSpore
ref over I, Sp : Freezing spore affecting insect
else Sp is a SlowSpore
ref over I, Sp : Slowing spore affecting insect
else Sp is a SpeedupSpore
ref over I, Sp : Speedup spore affecting insect
end
Sp -> T : removeEntity(Sp)
T --> Sp
Sp --> I

destroy Sp


@enduml