@startuml Insect moving

title Insect player moving to a tile

participant "I : Insect" as I
participant "CurrentTile : Tile" as Tx
participant "TargetTile : Tile" as Ty

activate I
activate Tx
activate Ty

'tell don't ask... 
I -> I : canMoveTo(TargetTile)
opt  have enough move points & path exists to desired tile (i.e. the result of canMoveTo())
I -> Tx : removeEntity(I)
Tx --> I
I -> Ty : addEntity(I)
Ty --> I
end



@enduml