@startuml Insect eating

title Insect player eating a spore

participant "i : Insect" as I
participant "sp : Spore" as Sp
participant "t : Tile" as T

activate I
activate T
activate Sp

I -> Sp : getEaten(i)
alt Sp is a CutSpore 
ref over I, Sp : Cut spore affecting insect
else Sp is a FreezeSpore
ref over I, Sp : Freezing spore affecting insect
else Sp is a SlowSpore
ref over I, Sp : Slowing spore affecting insect
else Sp is a SpeedupSpore
ref over I, Sp : Speedup spore affecting insect
end
Sp -> T : removeEntity(sp)
T --> Sp
Sp --> I

destroy Sp


@enduml