@startuml Insect moving

title Insect player moving to a tile

participant "i : Insect" as I
participant "currentTile : Tile" as Tx
participant "targetTile : Tile" as Ty

activate I
activate Tx
activate Ty

'tell don't ask... 
I -> I : canMoveTo(targetTile)
opt  have enough move points & path exists to desired tile (i.e. the result of canMoveTo())
I -> Tx : removeEntity(i)
Tx --> I
I -> Ty : addEntity(i)
Ty --> I
end



@enduml