@startuml Insect freeze times out

title Insect freeze times out

participant "M : Map" as M
participant "I : Insect" as I

activate M
activate I

M -> I : update()
opt hasFreezeEffect() 
    I -> I : setCut()
end
I --> M


@enduml