@startuml Insect thread cutting

title Insect cutting a thread


participant "I : Insect" as I
participant "M : Mycelium" as T
participant "T : Tile" as Tl
participant "Connected : Mycelium" as Mc
participant "Disconnected : Mycelium" as Md


activate I
activate T
activate Tl

opt Insect not under the influence of CutSpore
I -> T : detach()
T->Mc : <<construct>>

activate Mc

Mc-->T
T->Tl : addEntity(Connected)
Tl --> T
T->Md : <<construct>>

activate Md

Md-->T
T->Tl : addEntity(Disconnected)
Tl-->T

T->Tl : removeEntity(M)
Tl-->T

destroy T

end


@enduml