@startuml Mycelium growth

title Only one mycelium growing on Tekton

participant "f1 : Fungus" as F1
participant "f2 : Fungus" as F2
participant "tek: Tekton" as Tek
participant "m1 : Mycelium" as M1
participant "m2 : Mycelium" as M2
participant "t : Tile" as T

activate F1
activate F2
activate T
activate Tek


F1->Tek : growMycelium()
Tek --> F1 : true
F1 -> M1 ** : <<construct>>
activate M1
M1 --> F1
F1 -> T : addEntity()
T-->F1

F1-->F2

F2->Tek : growMycelium()
Tek --> F2 : false


@enduml