@startuml UC_IngameActiveRound

package "Use-Case Diagram for In-Game Active Round" #E6FFEB {

    left to right direction

    actor MushroomPlayer as "Mushroom Player"

    (SporeSpreading) as "Spore Spreading"
    (ThreadGrowing) as "Thread Growing"
    (MushroomHeadGrowing) as "Mushroom Head Growing"

    MushroomPlayer --> (SporeSpreading)
    MushroomPlayer --> (ThreadGrowing)
    MushroomPlayer --> (MushroomHeadGrowing)

    actor InsectPlayer as "Insect Player"

    (Movement) as "Movement"
    (SporeEating) as "Spore Eating"
    (ThreadCutting) as "Thread Cutting"

    InsectPlayer --> (Movement)
    Movement ..> (ThreadCutting) : <<extends>>
    Movement ..> (SporeEating) : <<extends>>
}

@enduml