@startuml UC_IngameActiveRound

package "Use-Case Diagram for In-Game active round" #E6FFEB {

    left to right direction

    actor GombaJatekos as "Gomba Játékos"

    (SporaSzoras) as "Spora Szórás"
    (szalNovesztes) as "Szál Növesztés"
    (gombafejNovesztes) as "Gombafej Növesztés"

    GombaJatekos --> (SporaSzoras)
    GombaJatekos --> (szalNovesztes)
    GombaJatekos --> (gombafejNovesztes)

    actor RovarJatekos as "Rovar Játékos"

    (Mozgas) as "Mozgás"
    (SporaEves) as "Spora Evés"
    (FonalVagas) as "Fonal Vágás"

    RovarJatekos --> (Mozgas)
    Mozgas ..> (FonalVagas) : <<extends>>
    Mozgas ..> (SporaEves) : <<extends>>
}

@enduml