@startuml UC_PauseHUD

package "Use-Case Diagram for In-Game pause HUD state" #ffe3da {

    left to right direction

    actor UserInput as "User-Input"

    (JatekMentes) as "Játék Mentés"
    (Fomenu) as "Főmenü"

    UserInput --> (JatekMentes)
    UserInput --> (Fomenu)
    
}

@enduml